# Generated by Django 4.1.5 on 2023-01-09 16:08

import PlayerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='passcode',
            field=models.PositiveIntegerField(default=PlayerApp.models.generate_passcode),
        ),
    ]
