# Generated by Django 4.1.5 on 2023-01-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerApp', '0002_player_channel_alter_player_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_seen',
        ),
    ]
