# Generated by Django 4.1.5 on 2023-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerApp', '0003_remove_player_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='system',
            field=models.TextField(blank=True),
        ),
    ]
