# Generated by Django 4.1.5 on 2023-01-09 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file', models.FileField(upload_to='media/')),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(editable=False, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
